![imagen](./img/guj36aqa.png)

# AGRESIONES LGTBIFÓBICAS EN ESPAÑA. 
## Evolución y análisis de subgrupos.

### TEMA

Este proyecto tiene como objetivo llevar a cabo un análisis exhaustivo de los delitos de odio registrados en España desde 2014 hasta 2023, segmentado por comunidades autónomas. La meta es identificar tendencias, patrones y variaciones en la incidencia de estos delitos a lo largo del tiempo y en diferentes regiones del país. Además, se buscará enriquecer el análisis con un dataset que incluya diversas identidades y realidades del colectivo LGTBIQ+.

### HIPÓTESIS

HIPÓTESIS PRINCIPAL: El aumento de las agresiones al colectivo LGTBIQ+ en el estado español.

SUB-HIPÓTESIS:

- Incremento de Delitos de Odio: Se hipotetiza que ha habido un aumento significativo en la cantidad de delitos de odio en España entre 2014 y 2023.

- Variabilidad por Comunidades Autónomas: Se plantea la hipótesis de que existen diferencias notables en la incidencia de delitos de odio entre comunidades autónomas.
- Identificación de Subgrupos Vulnerables: Se sugiere que dentro del colectivo LGTBIQ+, ciertos subgrupos (como personas trans, no binarias, bisexuales, asexuales) son más propensos a experimentar delitos de odio, lo que resalta la necesidad de un análisis detallado sobre las realidades y experiencias específicas de estos grupos.

- Impacto de la Legislación: Se plantea la hipótesis de que la implementación de políticas públicas y leyes contra la discriminación en ciertas comunidades autónomas está asociada con una disminución de los delitos de odio en esas áreas, sugiriendo que las medidas legislativas pueden ser efectivas en la reducción de la violencia.

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

**PRIMER DATASET**
Para obtener información sobre los registros de agresiones racistas y LGTBIfóbicas.
- Hechos conocidos por causa delitos de odio por CC.AA. desde el 2014 hasta el 2024.


**SEGUNDO DATASET**
Más detalle y variedd en clasificaicón de agresions LGTBIfóbicas.
- Informe de incidentes de odio motivados por LGTBIfobia. Intención de conseguir un csv o scrappear los datos: Completar los datos con modalidades e identidades. (Varios años)
(https://contraelodio.org/wp/informe-lgtbifobia-madrid/)

**TERCER DATASET**
Barómetro para comparar las agresiones de España con el resto de Europa.
- Special Eurobarometer 493: Discrimination in the EU (including LGBTI) (https://data.europa.eu/data/datasets/s2251_91_4_493_eng?locale=en)

**CUARTO DATASET**
Recurso sobre legislación en materia LGTBIQ+ en el mundo.
- Sexual Orientation Laws | EDA
(https://www.kaggle.com/code/chaitanya99/sexual-orientation-laws-eda/report)

**QUINTO DATASET**
Legislación en materia LGTBIQ+ en el estado español.
- ILGA dataset, Spain LGTBI (https://database.ilga.org/spain-lgbti)

SITUACIÓN DE LOS DATASETS

La gran mayoría no son dataset crudos, ni csv ni otro archivo del estilo. Son archivos .pdf de los que se scrappearán los datos y se trabajarán en crudo.

In [4]:
import pandas as pd
data1 = pd.read_csv("data/EDACC.AA._14-23.csv")
data1

,ORIENTACIÓN SEXUAL E IDENTIDAD DE GÉNERO,TOTAL NACIONAL,ANDALUCÍA,ARAGÓN,ASTURIAS (PRINCIPADO DE),BALEARS (ILLES),CANARIAS,CANTABRIA,CASTILLA Y LEÓN,CASTILLA - LA MANCHA,...,GALICIA,MADRID (COMUNIDAD DE),MURCIA (REGIÓN DE),NAVARRA (COMUNIDAD FORAL DE),PAÍS VASCO,RIOJA (LA),CIUDAD AUTÓNOMA DE CEUTA,CIUDAD AUTÓNOMA DE MELILLA,EN EL EXTRANJERO,DESCONOCIDO
0,2023,530,80,15,10,9,35,2,28,12,...,24,71,11,6,37,2,1,2,1,0
1,2022,464,68,9,9,2,18,6,15,20,...,11,51,10,8,88,0,0,1,0,0
2,2021,477,64,13,10,10,15,4,18,7,...,23,75,7,4,65,0,0,2,0,1
3,2020,282,36,3,1,5,14,1,8,7,...,5,42,4,4,45,0,0,7,0,0
4,2019,283,42,2,6,1,14,1,16,5,...,12,42,3,0,12,0,0,1,1,1
5,2018,259,36,6,5,6,5,1,5,7,...,10,42,4,1,34,1,0,2,1,0
6,2017,271,18,3,2,1,17,0,7,6,...,6,39,5,5,30,0,0,1,1,0
7,2016,230,30,5,1,4,2,3,4,4,...,10,42,2,10,30,0,0,3,0,0
8,2015,169,15,4,1,4,6,2,5,6,...,4,19,4,5,27,0,0,0,0,0
9,2014,513,188,36,15,41,16,0,19,15,...,43,26,11,9,14,0,2,2,2,0